/**
 * GENERATED by scripts/data/build-nph-census.ts — do not edit by hand.
 * Real NPH 2025-26 team entries (their own standings data); players are
 * always FICTIONAL (owner ruling — real players are minors).
 */
export interface NphCensusEntry {
  club: string
  league: "SL" | "D1" | "NPA" | "WNPA"
  division: string
  conference?: string
  teamLabel?: string
}

export const NPH_CENSUS: NphCensusEntry[] = [
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "Gr10",
    "conference": "DMV CHILL"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "Dragons de Gatineau",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "Royal Crown",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Royal Crown",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "Royal Crown",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "Royal Crown",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "Royal Crown",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "Royal Crown",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "Royal Crown",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Royal Crown",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "FEIA (Fort Erie)",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "FEIA (Fort Erie)",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "FEIA (Fort Erie)",
    "league": "D1",
    "division": "Senior Girls",
    "teamLabel": "FEIA Red"
  },
  {
    "club": "FEIA (Fort Erie)",
    "league": "D1",
    "division": "Scholastic",
    "teamLabel": "Fort Erie Prep"
  },
  {
    "club": "FEIA (Fort Erie)",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "FEIA (Fort Erie)",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "Ottawa Elite (incl. Prep)",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "Ottawa Elite (incl. Prep)",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "Ottawa Elite (incl. Prep)",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "Ottawa Elite (incl. Prep)",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "Ottawa Elite (incl. Prep)",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "Black, Gold"
  },
  {
    "club": "Ottawa Elite (incl. Prep)",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "Black, Gold"
  },
  {
    "club": "St. Jude's Prep/Academy",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "St. Jude's Prep/Academy",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "St. Jude's Prep/Academy",
    "league": "D1",
    "division": "Scholastic",
    "teamLabel": "Blue, White"
  },
  {
    "club": "St. Jude's Prep/Academy",
    "league": "D1",
    "division": "Scholastic",
    "teamLabel": "Blue, White"
  },
  {
    "club": "St. Jude's Prep/Academy",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "St. Jude's Prep/Academy",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "PDM Basketball",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "PDM Basketball",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "PDM Basketball",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "PDM Basketball",
    "league": "SL",
    "division": "Gr11"
  },
  {
    "club": "PDM Basketball",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "Burloak Elite",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Burloak Elite",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Burloak Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "DMV CHILL"
  },
  {
    "club": "Burloak Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "CE23 Academy",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "CE23 Academy",
    "league": "SL",
    "division": "Gr10",
    "conference": "DMV CHILL"
  },
  {
    "club": "CE23 Academy",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "CE23 Academy",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "MBA",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "MBA",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "MBA",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "MBA",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "NDL",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "NDL",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "NDL",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "NDL",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "North York Lions",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "North York Lions",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "North York Lions",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "North York Lions",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "RWI",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "RWI",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "RWI",
    "league": "SL",
    "division": "Gr11",
    "teamLabel": "RWI Kings, RWI 519"
  },
  {
    "club": "RWI",
    "league": "SL",
    "division": "Gr11",
    "teamLabel": "RWI Kings, RWI 519"
  },
  {
    "club": "Underdog Elite",
    "league": "SL",
    "division": "Gr9",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Underdog Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "Underdog Elite",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "Underdog Elite",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "Wiggins Elite",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Wiggins Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Wiggins Elite",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "Wiggins Elite",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "CKATT Basketball",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "CKATT Basketball",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "CKATT Basketball",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "City Above Elite",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "City Above Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "City Above Elite",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "Dropoff Elite",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "Dropoff Elite",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "Dropoff Elite",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "Edge School (Calgary)",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "Edge Varsity Black"
  },
  {
    "club": "Edge School (Calgary)",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Edge School (Calgary)",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "M and R Basketball",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "M and R Basketball",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "M and R Basketball",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "MC Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "MC Elite",
    "league": "SL",
    "division": "Gr12",
    "teamLabel": "GS, ARETE-White"
  },
  {
    "club": "MC Elite",
    "league": "SL",
    "division": "Gr12",
    "teamLabel": "GS, ARETE-White"
  },
  {
    "club": "Polaris Prep",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "Black, International"
  },
  {
    "club": "Polaris Prep",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "Black, International"
  },
  {
    "club": "Polaris Prep",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "SC Academy",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "SC Academy",
    "league": "SL",
    "division": "Gr12",
    "teamLabel": "ARETE, SC Academy Prep"
  },
  {
    "club": "SC Academy",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Simcoe United Spartans",
    "league": "SL",
    "division": "Gr9",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Simcoe United Spartans",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "Simcoe United Spartans",
    "league": "SL",
    "division": "Gr11"
  },
  {
    "club": "TNP",
    "league": "SL",
    "division": "Gr9",
    "teamLabel": "TNP East, PRIME"
  },
  {
    "club": "TNP",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "TNP",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Tall Pines Academy",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Tall Pines Academy",
    "league": "D1",
    "division": "Scholastic",
    "teamLabel": "Varsity"
  },
  {
    "club": "Tall Pines Academy",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "National"
  },
  {
    "club": "Toronto Lords",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "Toronto Lords",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "Toronto Lords",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "Tri-City (Prep/Academy)",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Tri-City (Prep/Academy)",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Tri-City (Prep/Academy)",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Vanguard North Prep",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "Vanguard North Prep",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "Vanguard North Prep",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "Westfield Secondary",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "Westfield Secondary",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Westfield Secondary",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "BCP",
    "league": "D1",
    "division": "Academy",
    "teamLabel": "BCP Provincial"
  },
  {
    "club": "BCP",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Brotherhood Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "Brotherhood Elite",
    "league": "SL",
    "division": "Gr11"
  },
  {
    "club": "Dynastie",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Dynastie",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "EM Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "EM Elite",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "Eurostep Basketball",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "Eurostep Basketball",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "G2S Game Changers",
    "league": "SL",
    "division": "Gr9",
    "teamLabel": "Gold–GS, Black–ARETE"
  },
  {
    "club": "G2S Game Changers",
    "league": "SL",
    "division": "Gr9",
    "teamLabel": "Gold–GS, Black–ARETE"
  },
  {
    "club": "Hamilton Transformation Academy",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Hamilton Transformation Academy",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "Hodan Prep",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Hodan Prep",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "King Heights",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "King Heights",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Kings Court Basketball",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "Kings Court Basketball",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Lincoln Prep",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Lincoln Prep",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Malton Sting Basketball",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "Malton Sting Basketball",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "North Toronto Huskies",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "North Toronto Huskies",
    "league": "SL",
    "division": "Gr12",
    "teamLabel": "DMV, Nkansah"
  },
  {
    "club": "ONL-X",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "ONL-X",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "Retro Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "Retro Elite",
    "league": "SL",
    "division": "Gr12",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "St. Michael's College School",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "St. Michael's College School",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "Tru Balance",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "Tru Balance",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Vaughan Panthers",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "Vaughan Panthers",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "Waterloo Wolverines Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Waterloo Wolverines Elite",
    "league": "SL",
    "division": "Gr12",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "West United Prep",
    "league": "SL",
    "division": "Gr12",
    "teamLabel": "Blue–GS, White–ARETE"
  },
  {
    "club": "West United Prep",
    "league": "SL",
    "division": "Gr12",
    "teamLabel": "Blue–GS, White–ARETE"
  },
  {
    "club": "YvY Elite",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "YvY Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "AAA Academy",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Against the Six",
    "league": "SL",
    "division": "Gr12"
  },
  {
    "club": "Alma Prep",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Alpha Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "B1CE London",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "BALL905 Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Barrie Buccaneers",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "Blessed Sacrament",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Brantford Hawks",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Burlington Force",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "Burlington Hoops Academy",
    "league": "SL",
    "division": "Gr10",
    "conference": "DMV CHILL"
  },
  {
    "club": "C.O.D.E Sports Academy",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "CB Elite",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "CSJV Prep Basketball QC",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Canada Central Prep",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Canadian Private School",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "Capital Courts",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "Cathedral",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Crestwood Prep",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "DEl1te",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "DFA Academy",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "Dundas Dynamo",
    "league": "SL",
    "division": "Gr12",
    "conference": "DMV CHILL"
  },
  {
    "club": "Durham Gators",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "Eastern Basketball Academy",
    "league": "SL",
    "division": "Gr10",
    "conference": "DMV CHILL"
  },
  {
    "club": "École St-Gabriel Escadron",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "Father Henry Carr",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "First Step Elite Gold",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Fitz Youth",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "Fundamentals First",
    "league": "SL",
    "division": "Gr9",
    "conference": "PRIME"
  },
  {
    "club": "Future Hope Academy",
    "league": "D1",
    "division": "Junior Boys"
  },
  {
    "club": "GT Elite",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "GYBA Gryphons",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "Grassroots Niagara",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "Gwillimbury Basketball United",
    "league": "SL",
    "division": "Gr11"
  },
  {
    "club": "HQ Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Hamilton Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "HoopHer",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "Hooptrotters OGs",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "J. Addison Jaguars",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "James Cardinal McGuigan",
    "league": "D1",
    "division": "Senior Girls"
  },
  {
    "club": "K9 Elite White",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "King's Christian Collegiate",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "Lead2Greatness",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Mississauga Monarchs",
    "league": "SL",
    "division": "Gr7"
  },
  {
    "club": "Momentum Basketball",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Niagara Prep",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "Norwood Stars",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Notre Dame Hounds SK",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "Oakville Panthers",
    "league": "SL",
    "division": "Gr9",
    "conference": "ARETE"
  },
  {
    "club": "Oakville Vytis",
    "league": "SL",
    "division": "JrGirls"
  },
  {
    "club": "Orangeville Prep",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "Orillia Lakers",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "Ottawa Prospects",
    "league": "SL",
    "division": "Gr11",
    "conference": "ARETE"
  },
  {
    "club": "Prolific Sports Academy",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "Ridley College",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Rothesay Netherwood School NB",
    "league": "NPA",
    "division": "Main"
  },
  {
    "club": "Sacred Heart Montreal",
    "league": "WNPA",
    "division": "Main"
  },
  {
    "club": "Southwest Academy",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "Ste Cecile Academy",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "TC Soldiers",
    "league": "SL",
    "division": "Gr8"
  },
  {
    "club": "Team CB",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "The Conglomerate",
    "league": "SL",
    "division": "Gr12",
    "conference": "ARETE"
  },
  {
    "club": "Thornhill Thunder",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "Tornades Basketball",
    "league": "SL",
    "division": "Gr11",
    "conference": "DMV CHILL"
  },
  {
    "club": "Toronto Top Tier East",
    "league": "SL",
    "division": "Gr10",
    "conference": "PRIME"
  },
  {
    "club": "Uchenna Academy",
    "league": "D1",
    "division": "Scholastic"
  },
  {
    "club": "Union Elite",
    "league": "SL",
    "division": "Gr10",
    "conference": "GAME SPEAKS"
  },
  {
    "club": "Victory Prep",
    "league": "D1",
    "division": "Academy"
  },
  {
    "club": "West Ottawa",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  },
  {
    "club": "William Prep",
    "league": "D1",
    "division": "Junior Girls"
  },
  {
    "club": "YASO Basketball Academy Black",
    "league": "SL",
    "division": "Gr10",
    "conference": "ARETE"
  }
]
