/**
 * The walkthrough cast. Every scene pulls names, fees and venues from here,
 * so recasting the demo (e.g. to NPH league names once the owner rules)
 * means editing this one file.
 */
export const DW = {
  league: "Metro Youth Basketball League",
  season: "Winter 2026-27",
  club: "Ridgeview Rockets",
  club2: "North Star Storm",
  club3: "Lakeside Lords",
  club4: "Harbour City Chargers",
  team: "U13 Boys Rep",
  venue: "Maplewood CC",
  gym: "Gym A",
  gym2: "Gym B",
  venue2: "Brookfield High",
  tryoutFee: "$25",
  seasonFee: "$2,400",
  deposit: "$500",
  installments: "4 × $475",
  teamFee: "$1,850",
  players: [
    "Jordan Lee",
    "Marcus Okafor",
    "Theo Brandt",
    "Isaiah Grant",
    "Owen Park",
    "Malik Thompson",
    "Caleb Rossi",
    "Devin Clarke",
    "Noah Fielding",
    "Andre Silva",
    "Liam Chow",
    "Ethan Brooks",
  ],
  headCoach: "Dana Whitfield",
  assistantCoach: "Alex Romero",
  teamManager: "Priya Nair",
  invitedCoach: "coach.marcus@gmail.com",
  refs: ["Mike Reyes", "Sofia Grant", "Jamal Carter"],
  parent: "Sam Lee",
  kid: "Jordan Lee",
  kidYear: "2013",
} as const
